spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/countries_dev
    username: postgres
    password: ec210885
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
