version: '3.8'
services:
  postgresql:
    image: postgres
    container_name: postgres_contries
    environment:
      POSTGRES_HOST: postgresql
      POSTGRES_DATABASE: countries_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_ROOT_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data